[package]
name = "y2015"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
anyhow = "1.0.63"
md-5 = "0.10"
hex = "0.4.3"